### ISSUE TITLE
User permision

### ISSUE THREAD

**Issue by MohammaddReza** [silverstripe/moduleratings#14]
Could it be possible to access a specific group of users?
And each user will vote once per page

**Comment by robbieaverill** [comment]
Hi @MohammaddReza, I'm not really sure what you're asking for here. This package assigns automated ratings to SilverStripe modules, there's no user controlled input at the moment (e.g. voting systems). Could you elaborate please?

**Comment by ScopeyNZ** [comment]
Hi @MohammaddReza. I'll close this issue for now. If you're looking for an addon that lets you rate pages on your SilverStripe CMS website try searching on https://addons.silverstripe.org
